script: "bundle exec rake test"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head

gemfile:
  - gemfiles/active_record_30.gemfile
  - gemfiles/active_record_31.gemfile
  - gemfiles/active_record_32.gemfile
  - gemfiles/active_record_40.gemfile
  - gemfiles/active_record_41.gemfile
  - gemfiles/active_record_edge.gemfile

matrix:
  fast_finish: true
