script: "bundle install && bundle exec rake test"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head

gemfile:
  - gemfiles/activerecord_30.gemfile
  - gemfiles/activerecord_31.gemfile
  - gemfiles/activerecord_32.gemfile
  - gemfiles/activerecord_40.gemfile
  - gemfiles/activerecord_41.gemfile
  - gemfiles/activerecord_edge.gemfile

matrix:
  fast_finish: true
